# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 49ff184354e4bcd59786c08ef71df0462f6f977ee1dbb96d309151626dd50c40fc8fffda4a7be88b581bd6d21ee9ee84c586c61d68cf94d1dd5446492419dcce

test:
  secret_key_base: 16135439898ead5155aebbe58c70426d6c7ed15b3a5d4407e709317af5632d787a8a410e1aafd63ddf0cd796ac59a8a0d17bbff6b064f86b60e620b50bf5c0a9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
